services:
  ros_app:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - ros_network
    tty: true
    stdin_open: true

networks:
  ros_network:
    driver: bridge