version: '3.8'

services:
  ros_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  

    networks:
      - ros_network
    tty: true
    stdin_open: true

networks:
  ros_network:
    driver: bridge

